SmartDocRetrieval/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'doc_browse/', include('RetrievalCore.urls', namespace='RetrievalCore')),
    re_path(r'user/', include('RetrievalCore.urls', namespace='User'))
]

apps/RetrievalCore/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/4/6 19:51
# @Author  : Mr.Robot
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.urls import path, re_path
from RetrievalCore import views

urlpatterns = [
    re_path(r'^list/', views.DocumentListView.as_view(), name="document_list"),
    re_path(r'^detail/(?P<document_id>\d+)/(?P<session_id>\d+)/$', views.DocumentDetailView.as_view(), name="document_detail"),
    path('login/', views.UserLogin.as_view(), name="user_login"),
    path('register/', views.UserRegister.as_view(), name="user_register"),
    re_path(r'^assess/', views.PreferenceAssess.as_view(), name="preference_assess"),
    re_path(r'^preference_customize/', views.UserPreference.as_view(), name="user_preference"),
    re_path(r'^record_preference/(?P<user_id>\d+)/', views.RecordPreference.as_view(), name="record_preference")
]

app_name = 'RetrievalCore'

templates/doc_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ document.title }}</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/frame/bootstrap-slider.css">
    <link rel="stylesheet" href="/static/css/detail.css">
</head>
<body>

<button class="btn btn-danger back-btn" onclick="window.close()">Back</button>

<main class="main-content">
    <div class="border-bottom">
        <h1 class="detail-title" document-id="{{ document.id }}" document-classification="{{ document.classification }}">{{ document.title }}</h1>
    </div>
    <div class="border-bottom">
        <ul class="detail-author-list">
            <li class="detail-label">Authors:</li>
            {% for author in document.get_authors %}
            <li class="detail-author-item">{{ author }},</li>
            {% endfor %}
        </ul>
    </div>
    <div class="border-bottom">
        <span class="detail-label">Publication:</span>
        <span class="detail-dot-separator">
            <span class="detail-publication">{{ document.publication }}</span>
        </span>
        <span class="detail-dot-separator">
            <span class="detail-doc-url">{{ document.doi_url }}</span>
        </span>
    </div>

    <div class="abstract-container">
        <div class="detail-block-title">
            <h2 class="detail-section-label">
                Abstract
            </h2>
        </div>
        <div class="abstract-section">
            <p>{{ document.abstract }}</p>
        </div>
    </div>
    <div class="reference-container">
        <div class="detail-block-title">
            <h2 class="detail-section-label">
                References
            </h2>
        </div>
        <ol class="reference-list">
            {% for reference in document.get_references %}
            <li class="reference-item">
                <span class="reference-note">{{ reference }}</span>
            </li>
            {% endfor %}
        </ol>
    </div>
</main>
<div class="detail-bottom-container">
    <div class="detail-bottom">
        <label for="user_relevance" class="relevance-label">Relevance-Feedback:(0-1)</label>
        <input id="user_relevance" data-slider-id='user-relevance-slider' type="text" data-slider-min="0"
                       data-slider-max="1" data-slider-step="0.01" data-slider-value="0"/>
        <span class="preference-label">Interest:
            <span id="user-relevance-label" class="classification" style="width: 48px;display: inline-block;">0</span>
        </span>
        {% csrf_token %}
        <button class="btn btn-primary detail-relevance-btn" type="button" onclick="submit_relevance()">Feedback My Interest</button>
    </div>
</div>

<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap-slider.js"></script>
<script type="text/javascript">
    new Slider("#user_relevance").on("slide", function (event) {
        $("#user-relevance-label").text(event.value);
    });
</script>
<script type="text/javascript">
    function submit_relevance() {
        let user_relevance = parseFloat($('#user-relevance-label').text());
        let title = $('.detail-title')[0];
        let document_id = parseFloat(title.getAttribute("document-id"));
        let document_classification = parseInt(title.getAttribute("document-classification"));

        let session_relevance = localStorage.getItem("session_relevance");
        if (session_relevance == null)
            session_relevance = new Map();
        else
            session_relevance = JSON.parse(session_relevance);
        session_relevance[document_id] = {classification: document_classification, relevance: user_relevance};
        localStorage.setItem("session_relevance", JSON.stringify(session_relevance));
    }
</script>
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SmartDocRetrieval</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/list.css">
</head>
<body>

<button type="button" class="btn btn-primary preference-customize-btn" onclick="window.open('{% url 'User:user_preference' %}{{ user_id }}', 'self')">Preference Custom</button>
<button type="button" class="btn btn-info preference-record-btn" onclick="window.open('{% url 'User:record_preference' user_id=user_id %}', 'self')">Exit System</button>

<ul>
    {% for document in documents %}
    <li class="doc_list_card">
        <h5 class="doc_title" onclick="window.open('{% url 'RetrievalCore:document_detail' document_id=document.id session_id=session.id %}', 'self')">{{ document.title }}</h5>
        <ul class="author_list">
            {% for author in document.get_authors %}
            <li class="author_item">{{ author }},</li>
            {% endfor %}
        </ul>
        <div class="doc_profile">{{ document.publication }}</div>
        <div class="doc_subtract">{{ document.abstract }}</div>
    </li>
    {% endfor %}
</ul>
{% csrf_token %}
<div class="list-bottom" session-id="{{ session.id }}">
    <div class="btn-danger exit-session-button" onclick="exit_session()">Exit Session</div>
</div>

<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript">
    function exit_session() {
        let user_relevance = localStorage.getItem("session_relevance");
        user_relevance = JSON.parse(user_relevance);
        let session_id = $(".list-bottom")[0].getAttribute("session-id");
        $.ajax({
            url: "{% url 'RetrievalCore:document_list' %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "session_relevance": JSON.stringify(user_relevance),
                "session_id": parseInt(session_id),
                "user_id": "{{ user_id }}"
            },
            async: false,
            success: function (result) {
                window.location = '{% url 'User:preference_assess' %}{{ session.id }}/';
            }
        });
    }
</script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login-SmartDocRetrieval</title>
    <link href="/static/css/frame/bootstrap.css" rel="stylesheet"/>
</head>
<body>
<form id="form1" class="well" style="width: 30em; margin: auto; margin-top: 150px;">
    <h3>User Login</h3>
    <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1">
                  <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
              </span>
        <input id="userName" type="text" class="form-control" placeholder="Account" aria-describedby="sizing-addon1"/>
    </div>
    <br/>
    <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1">
                  <i class="glyphicon glyphicon-lock"></i>
              </span>
        <input type="password" id="password" class="form-control" placeholder="Password" aria-describedby="sizing-addon1"/>
    </div>
    <button type="button" class="btn btn-success btn-block" style="margin-top: 15px">Login</button>
    {% csrf_token %}
</form>
<div>
    <a class="btn btn-sm btn-white btn-block" style="text-align: center;" href="{% url 'User:user_register' %}">
        <h6>Not have an account?Go Register</h6>
    </a>
</div>
<script src="/static/js/frame/jquery.min.js"></script>
<script src="/static/js/frame/bootstrap.js"></script>
<script>
    $("#form1").on("click", ".btn", function (e) {
        let radioValue = $('input:radio[name="kind"]:checked').val();
        let formData = $("#form1").serialize();
        $.ajax({
            url: "{% url 'User:user_login' %}",
            type: "post",
            async: false,
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "username": $("#userName").val(),
                "password": $("#password").val()
            },
            dataType: "json",
            success: function (result) {
                if (result["success"] && result["redirect"] != null) {
                    window.location = `${result["redirect"]}`
                } else if (result["success"]) {
                    window.location = `/doc_browse/list/${result["user_id"]}`;
                } else {
                    alert(result["msg"]);
                }
            }
        });
    })
</script>
</body>
</html>

templates/preference.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文献检索系统</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/list.css">
</head>
<body>

<ul>
    {% for document in documents %}
    <li class="doc_list_card">
        <input type="checkbox" class="custom-checkbox custom-control-input" id="{{ document.id }}" name="{{ document.id }}">
        <h5 class="doc_title" onclick="window.open('{% url 'RetrievalCore:document_detail' document_id=document.id session_id=session.id %}', 'self')">{{ document.title }}</h5>
        <ul class="author_list">
            {% for author in document.get_authors %}
            <li class="author_item">{{ author }},</li>
            {% endfor %}
        </ul>
        <div class="doc_profile">{{ document.publication }}</div>
        <div class="doc_subtract">{{ document.abstract }}</div>
    </li>
    {% endfor %}
</ul>
{% csrf_token %}
<div class="list-bottom" session-id="{{ session.id }}">
    <div class="btn-danger exit-session-button" onclick="exit_session()">退出会话</div>
</div>

<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript">
    function exit_session() {
        let user_relevance = localStorage.getItem("session_relevance");
        user_relevance = JSON.parse(user_relevance);
        let session_id = $(".list-bottom")[0].getAttribute("session-id");
        $.ajax({
            url: "{% url 'RetrievalCore:document_list' %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "session_relevance": JSON.stringify(user_relevance),
                "session_id": parseInt(session_id)
            },
            async: false,
        });
    }
</script>
</body>
</html>

templates/preference_assess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SmartDocRetrieval</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/list.css">
    <link rel="stylesheet" type="text/css" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/static/css/frame/font-awesome.css">
</head>
<body>

<ul session-id="{{ session.id }}">
    {% for document in documents %}
    <li class="doc_list_card">
        <div class=" checkbox checkbox-primary">
            <input id="checkbox{{ document.id }}" class="custom-checkbox custom-control styled document-checkbox" type="checkbox" document-id="{{ document.id }}">
            <label for="checkbox{{ document.id }}">
                Relevant Result
            </label>
        </div>
        <h5 class="doc_title" onclick="window.open('{% url 'RetrievalCore:document_detail' document_id=document.id session_id=session.id %}', 'self')">{{ document.title }}</h5>
        <ul class="author_list">
            {% for author in document.get_authors %}
            <li class="author_item">{{ author }},</li>
            {% endfor %}
        </ul>
        <div class="doc_profile">{{ document.publication }}</div>
        <div class="doc_subtract">{{ document.abstract }}</div>
    </li>
    {% endfor %}
</ul>
{% csrf_token %}
<div class="list-bottom">
    <div class="btn-secondary exit-session-button" onclick="exit_session()">Submit Preference</div>
</div>

<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript">
    function exit_session() {
        let user_preference = [];
        document.querySelectorAll(".document-checkbox").forEach(box => {
            user_preference.push({
                "document_id": box.getAttribute("document-id"),
                "user_relevant": box.checked
            });
        });
        let session_id = document.querySelectorAll(`ul`)[0].getAttribute("session-id");
        $.ajax({
            url: "{% url 'User:preference_assess' %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "user_preference": JSON.stringify(user_preference),
                "session_id": parseInt(session_id)
            },
            async: false,
            success: function (result) {
                window.location = '{% url 'RetrievalCore:document_list' %}{{ user.id }}';
            }
        });
    }
</script>
</body>
</html>

templates/preference_customize.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Preference-Customize</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/frame/bootstrap-slider.css">
    <link rel="stylesheet" href="/static/css/list.css">
    <link rel="stylesheet" href="/static/css/preference_customize.css">
</head>
<body>

<button class="btn btn-danger back-btn" onclick="window.close()">Back</button>

<ul class="category-list">
    {% for category in classification %}
        <li class="category-item border-bottom">
            <label for="category-{{ category.category_code }}"
                   class="category-label">{{ category.category_name }}</label>
            <input id="category-{{ category.category_code }}"
                   data-slider-id='category-slider-{{ category.category_code }}' type="text" data-slider-min="0"
                   data-slider-max="1" data-slider-step="0.01" data-slider-value="{{ category.interest_value }}"/>
            <span class="preference-label">Interest:
                <span id="category-label-{{ category.category_code }}" class="classification">{{ category.interest_value }}</span>
            </span>
        </li>
    {% endfor %}
</ul>
<div class="btn-container">
    <div class="btn-info submit-btn" onclick="preference_customize()">Submit</div>
    <div class="btn-secondary skip-btn" onclick="preference_initialize()">Skip</div>
</div>
{% csrf_token %}
<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap-slider.js"></script>
<script type="text/javascript">
    {% for category in classification %}
        new Slider("#category-{{ category.category_code }}").on("slide", function (event) {
            $("#category-label-{{ category.category_code }}").text(event.value);
        });
    {% endfor %}
</script>
<script type="text/javascript">
    function preference_customize() {
        let user_preference = [];
        document.querySelectorAll(".classification").forEach(input_box => {
            try {
                let prefer_value = parseFloat($(input_box).text());
                if (isNaN(prefer_value)) {
                    user_preference.push(0);
                } else {
                    user_preference.push(prefer_value);
                }
            } catch (e) {
                user_preference.push(0);
            }
        });
        $.ajax({
            url: "{% url 'User:user_preference' %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "user_id": {{user.id}},
                "user_preference": JSON.stringify(user_preference)
            },
            async: false,
            success: function (result) {
                if (result["success"]) {
                    window.location = `/doc_browse/list/${result["user_id"]}`;
                }
            }
        });
    }

    function preference_initialize() {
        $.ajax({
            url: "{% url 'User:user_preference' %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "user_id": {{user.id}},
                "user_preference": JSON.stringify(null)
            },
            async: false,
            success: function (result) {
                if (result["success"]) {
                    window.location = `/doc_browse/list/${result["user_id"]}`;
                }
            }
        });
    }
</script>
</body>
</html>

templates/record_preference.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Preference-Submit</title>
    <link rel="stylesheet" href="/static/css/frame/bootstrap.css">
    <link rel="stylesheet" href="/static/css/frame/bootstrap-slider.css">
    <link rel="stylesheet" href="/static/css/list.css">
    <link rel="stylesheet" href="/static/css/preference_customize.css">
</head>
<body>

<ul class="category-list">
    {% for category in classification %}
        <li class="category-item border-bottom">
            <label for="category-{{ category.category_code }}"
                   class="category-label">{{ category.category_name }}</label>
            <input id="category-{{ category.category_code }}"
                   data-slider-id='category-slider-{{ category.category_code }}' type="text" data-slider-min="0"
                   data-slider-max="1" data-slider-step="0.01" data-slider-value="0"/>
            <span class="preference-label">Interest:
                <span id="category-label-{{ category.category_code }}" class="classification">0</span>
            </span>
        </li>
    {% endfor %}
</ul>
<div class="btn-container">
    <div class="btn-info submit-btn" onclick="submit_preference()">Submit</div>
</div>
{% csrf_token %}
<script type="text/javascript" src="/static/js/frame/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap.js"></script>
<script type="text/javascript" src="/static/js/frame/bootstrap-slider.js"></script>
<script type="text/javascript">
    {% for category in classification %}
        new Slider("#category-{{ category.category_code }}").on("slide", function (event) {
            $("#category-label-{{ category.category_code }}").text(event.value);
        });
    {% endfor %}
</script>
<script type="text/javascript">
    function submit_preference() {
        let user_preference = [];
        document.querySelectorAll(".classification").forEach(input_box => {
            try {
                let prefer_value = parseFloat($(input_box).text());
                if (isNaN(prefer_value)) {
                    user_preference.push(0);
                } else {
                    user_preference.push(prefer_value);
                }
            } catch (e) {
                user_preference.push(0);
            }
        });
        $.ajax({
            url: "{% url 'User:record_preference' user_id=user.id %}",
            type: "post",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "user_id": {{user.id}},
                "user_preference": JSON.stringify(user_preference)
            },
            async: false,
            success: function (result) {
                if (result["success"]) {
                    // window.location = `/doc_browse/list/${result["user_id"]}`;
                }
            }
        });
    }
</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register-SmartDocRetrieval</title>
    <link href="/static/css/frame/bootstrap.css" rel="stylesheet"/>
</head>
<body>
<form id="form1" class="well" style="width: 30em; margin: auto; margin-top: 150px;">
    <h3>Register</h3>
    <div class=" input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1">
                  <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
              </span>
        <input id="userName" type="text" class="form-control" placeholder="Account" aria-describedby="sizing-addon1"/>
    </div>
    <br/>
    <div class="input-group input-group-md">
              <span class="input-group-addon" id="sizing-addon1">
                  <i class="glyphicon glyphicon-lock"></i>
              </span>
        <input type="password" id="password" class="form-control" placeholder="Password" aria-describedby="sizing-addon1"/>
    </div>
    <button type="button" class="btn btn-success btn-block" onclick="register()" style="margin-top: 15px">Register</button>
    {% csrf_token %}
</form>
<div>
    <a class="btn btn-sm btn-white btn-block" style="text-align: center;" href="{% url 'User:user_login' %}">
    <h6>Already have an account?Login</h6>
</a>
</div>
<script src="/static/js/frame/jquery.min.js"></script>
<script src="/static/js/frame/bootstrap.js"></script>
<script>
    function register() {
        $.ajax({
            url: "{% url 'User:user_register' %}",
            type: "post",
            data: {
                'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']")[0].getAttribute("value"),
                "username": $("#userName").val(),
                "password": $("#password").val()
            },
            dataType: "json",
            success: function (result) {
                if (result["success"]) {
                    window.location = "{% url 'User:user_login' %}";
                } else {
                    alert(result["msg"]);
                }
            }
        });
    }
</script>
</body>
</html>